print("Hello India Team")
print("Hello team under devops we are learning GIT")
print("today i am using git basic commands")
print("changes are made in master repos")
print("i created new project called DemoDevOps")
print("user-2 modified the code in global master repos")
print("This is feature1 change")
print("new branch features/f1")
print("welcome to user-2 ... edited by user-1")
print("changes are made in f1 branch")
